name: publish autopilot

on:
  workflow_call:
    inputs:
      version:
        description: 'Version to use for Docker tags'
        required: false
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to use for Docker tags'
        required: false
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Get version
        run: |
          if [ -n "${{ inputs.version }}" ]; then
            echo "LERNA_VERSION=${{ inputs.version }}" >> $GITHUB_ENV
          else
            lerna_version=$(node -p "require('./lerna.json').version")
            echo "LERNA_VERSION=$lerna_version" >> $GITHUB_ENV
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Publish Autopilot to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: fonoster/autopilot
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          context: .
          dockerfile: mods/autopilot/Dockerfile
          tags: "latest,${{ env.LERNA_VERSION }}"
          platforms: linux/amd64,linux/arm64